import 'dart:collection';
import 'dart:ui';
import 'package:flutter/material.dart';

class MaterialColors {
  static final Map<Color, List<Color>> materialColorMapping =
      LinkedHashMap<Color, List<Color>>.from({
    Colors.red.shade500: redList,
    Colors.pink.shade500: pinkList,
    Colors.purple.shade500: purpleList,
    Colors.deepPurple.shade500: deepPurpleList,
    Colors.indigo.shade500: indigoList,
    Colors.blue.shade500: blueList,
    Colors.lightBlue.shade500: lightBlueList,
    Colors.cyan.shade500: cyanList,
    Colors.teal.shade500: tealList,
    Colors.green.shade500: greenList,
    Colors.lightGreen.shade500: lightGreenList,
    Colors.lime.shade500: limeList,
    Colors.yellow.shade500: yellowList,
    Colors.amber.shade500: amberList,
    Colors.orange.shade500: orangeList,
    Colors.deepOrange.shade500: deepOrangeList,
    Colors.brown.shade500: brownList,
    Colors.grey.shade500: greyList,
    Colors.blueGrey.shade500: blueGreyList,
    Colors.black: [],
    Colors.white: [],
  });

  static final List<Color> colors = [
    Colors.red.shade500,
    Colors.pink.shade500,
    Colors.purple.shade500,
    Colors.deepPurple.shade500,
    Colors.indigo.shade500,
    Colors.blue.shade500,
    Colors.lightBlue.shade500,
    Colors.cyan.shade500,
    Colors.teal.shade500,
    Colors.green.shade500,
    Colors.lightGreen.shade500,
    Colors.lime.shade500,
    Colors.yellow.shade500,
    Colors.amber.shade500,
    Colors.orange.shade500,
    Colors.deepOrange.shade500,
    Colors.brown.shade500,
    Colors.grey.shade500,
    Colors.blueGrey.shade500,
    Colors.black,
    Colors.white,
  ];
  static final List<List<Color>> subColors = [
    redList,
    pinkList,
    purpleList,
    deepPurpleList,
    indigoList,
    blueList,
    lightBlueList,
    cyanList,
    tealList,
    greenList,
    lightGreenList,
    limeList,
    yellowList,
    amberList,
    orangeList,
    deepOrangeList,
    brownList,
    greyList,
    blueGreyList,
    [],
    [],
  ];

  static final List<Color> redList = [
    Colors.red.shade50,
    Colors.red.shade100,
    Colors.red.shade200,
    Colors.red.shade300,
    Colors.red.shade400,
    Colors.red.shade500,
    Colors.red.shade600,
    Colors.red.shade700,
    Colors.red.shade800,
    Colors.red.shade900,
    const Color(0xFFFF8A80),
    const Color(0xFFFF5252),
    const Color(0xFFFF1744),
    const Color(0xFFD50000),
  ];

  static final List<Color> pinkList = [
    Colors.pink.shade50,
    Colors.pink.shade100,
    Colors.pink.shade200,
    Colors.pink.shade300,
    Colors.pink.shade400,
    Colors.pink.shade500,
    Colors.pink.shade600,
    Colors.pink.shade700,
    Colors.pink.shade800,
    Colors.pink.shade900,
    const Color(0xFFFF80AB),
    const Color(0xFFFF4081),
    const Color(0xFFF50057),
    const Color(0xFFC51162)
  ];

  static final List<Color> purpleList = [
    Colors.purple.shade50,
    Colors.purple.shade100,
    Colors.purple.shade200,
    Colors.purple.shade300,
    Colors.purple.shade400,
    Colors.purple.shade500,
    Colors.purple.shade600,
    Colors.purple.shade700,
    Colors.purple.shade800,
    Colors.purple.shade900,
    const Color(0xFFEA80FC),
    const Color(0xFFE040FB),
    const Color(0xFFD500F9),
    const Color(0xFFAA00FF)
  ];

  static final List<Color> deepPurpleList = [
    Colors.deepPurple.shade50,
    Colors.deepPurple.shade100,
    Colors.deepPurple.shade200,
    Colors.deepPurple.shade300,
    Colors.deepPurple.shade400,
    Colors.deepPurple.shade500,
    Colors.deepPurple.shade600,
    Colors.deepPurple.shade700,
    Colors.deepPurple.shade800,
    Colors.deepPurple.shade900,
    const Color(0xFFB388FF),
    const Color(0xFF7C4DFF),
    const Color(0xFF651FFF),
    const Color(0xFF6200EA)
  ];
  static final List<Color> indigoList = [
    Colors.indigo.shade50,
    Colors.indigo.shade100,
    Colors.indigo.shade200,
    Colors.indigo.shade300,
    Colors.indigo.shade400,
    Colors.indigo.shade500,
    Colors.indigo.shade600,
    Colors.indigo.shade700,
    Colors.indigo.shade800,
    Colors.indigo.shade900,
    const Color(0xFF8C9EFF),
    const Color(0xFF536DFE),
    const Color(0xFF3D5AFE),
    const Color(0xFF304FFE)
  ];

  static final List<Color> blueList = [
    Colors.blue.shade50,
    Colors.blue.shade100,
    Colors.blue.shade200,
    Colors.blue.shade300,
    Colors.blue.shade400,
    Colors.blue.shade500,
    Colors.blue.shade600,
    Colors.blue.shade700,
    Colors.blue.shade800,
    Colors.blue.shade900,
    const Color(0xFF82B1FF),
    const Color(0xFF448AFF),
    const Color(0xFF2979FF),
    const Color(0xFF2962FF)
  ];

  static final List<Color> lightBlueList = [
    Colors.lightBlue.shade50,
    Colors.lightBlue.shade100,
    Colors.lightBlue.shade200,
    Colors.lightBlue.shade300,
    Colors.lightBlue.shade400,
    Colors.lightBlue.shade500,
    Colors.lightBlue.shade600,
    Colors.lightBlue.shade700,
    Colors.lightBlue.shade800,
    Colors.lightBlue.shade900,
    const Color(0xFF80D8FF),
    const Color(0xFF40C4FF),
    const Color(0xFF00B0FF),
    const Color(0xFF0091EA)
  ];
  static final List<Color> cyanList = [
    Colors.cyan.shade50,
    Colors.cyan.shade100,
    Colors.cyan.shade200,
    Colors.cyan.shade300,
    Colors.cyan.shade400,
    Colors.cyan.shade500,
    Colors.cyan.shade600,
    Colors.cyan.shade700,
    Colors.cyan.shade800,
    Colors.cyan.shade900,
    const Color(0xFF84FFFF),
    const Color(0xFF18FFFF),
    const Color(0xFF00E5FF),
    const Color(0xFF00B8D4)
  ];
  static final List<Color> tealList = [
    Colors.teal.shade50,
    Colors.teal.shade100,
    Colors.teal.shade200,
    Colors.teal.shade300,
    Colors.teal.shade400,
    Colors.teal.shade500,
    Colors.teal.shade600,
    Colors.teal.shade700,
    Colors.teal.shade800,
    Colors.teal.shade900,
    const Color(0xFFA7FFEB),
    const Color(0xFF64FFDA),
    const Color(0xFF1DE9B6),
    const Color(0xFF00BFA5)
  ];
  static final List<Color> greenList = [
    Colors.green.shade50,
    Colors.green.shade100,
    Colors.green.shade200,
    Colors.green.shade300,
    Colors.green.shade400,
    Colors.green.shade500,
    Colors.green.shade600,
    Colors.green.shade700,
    Colors.green.shade800,
    Colors.green.shade900,
    const Color(0xFFB9F6CA),
    const Color(0xFF69F0AE),
    const Color(0xFF00E676),
    const Color(0xFF00C853)
  ];
  static final List<Color> lightGreenList = [
    Colors.lightGreen.shade50,
    Colors.lightGreen.shade100,
    Colors.lightGreen.shade200,
    Colors.lightGreen.shade300,
    Colors.lightGreen.shade400,
    Colors.lightGreen.shade500,
    Colors.lightGreen.shade600,
    Colors.lightGreen.shade700,
    Colors.lightGreen.shade800,
    Colors.lightGreen.shade900,
    const Color(0xFFCCFF90),
    const Color(0xFFB2FF59),
    const Color(0xFF76FF03),
    const Color(0xFF64DD17)
  ];
  static final List<Color> limeList = [
    Colors.lime.shade50,
    Colors.lime.shade100,
    Colors.lime.shade200,
    Colors.lime.shade300,
    Colors.lime.shade400,
    Colors.lime.shade500,
    Colors.lime.shade600,
    Colors.lime.shade700,
    Colors.lime.shade800,
    Colors.lime.shade900,
    const Color(0xFFF4FF81),
    const Color(0xFFEEFF41),
    const Color(0xFFC6FF00),
    const Color(0xFFAEEA00)
  ];
  static final List<Color> yellowList = [
    Colors.yellow.shade50,
    Colors.yellow.shade100,
    Colors.yellow.shade200,
    Colors.yellow.shade300,
    Colors.yellow.shade400,
    Colors.yellow.shade500,
    Colors.yellow.shade600,
    Colors.yellow.shade700,
    Colors.yellow.shade800,
    Colors.yellow.shade900,
    const Color(0xFFFFFF8D),
    const Color(0xFFFFFF00),
    const Color(0xFFFFEA00),
    const Color(0xFFFFD600),
  ];
  static final List<Color> amberList = [
    Colors.amber.shade50,
    Colors.amber.shade100,
    Colors.amber.shade200,
    Colors.amber.shade300,
    Colors.amber.shade400,
    Colors.amber.shade500,
    Colors.amber.shade600,
    Colors.amber.shade700,
    Colors.amber.shade800,
    Colors.amber.shade900,
    const Color(0xFFFFE57F),
    const Color(0xFFFFD740),
    const Color(0xFFFFC400),
    const Color(0xFFFFAB00),
  ];
  static final List<Color> orangeList = [
    Colors.orange.shade50,
    Colors.orange.shade100,
    Colors.orange.shade200,
    Colors.orange.shade300,
    Colors.orange.shade400,
    Colors.orange.shade500,
    Colors.orange.shade600,
    Colors.orange.shade700,
    Colors.orange.shade800,
    Colors.orange.shade900,
    const Color(0xFFFFD180),
    const Color(0xFFFFAB40),
    const Color(0xFFFF9100),
    const Color(0xFFFF6D00),
  ];
  static final List<Color> deepOrangeList = [
    Colors.deepOrange.shade50,
    Colors.deepOrange.shade100,
    Colors.deepOrange.shade200,
    Colors.deepOrange.shade300,
    Colors.deepOrange.shade400,
    Colors.deepOrange.shade500,
    Colors.deepOrange.shade600,
    Colors.deepOrange.shade700,
    Colors.deepOrange.shade800,
    Colors.deepOrange.shade900,
    const Color(0xFFFF9E80),
    const Color(0xFFFF4E40),
    const Color(0xFFFF3D00),
    const Color(0xFFFF2C00),
  ];

  static final List<Color> brownList = [
    Colors.brown.shade50,
    Colors.brown.shade100,
    Colors.brown.shade200,
    Colors.brown.shade300,
    Colors.brown.shade400,
    Colors.brown.shade500,
    Colors.brown.shade600,
    Colors.brown.shade700,
    Colors.brown.shade800,
    Colors.brown.shade900
  ];
  
  static final List<Color> greyList = [
    Colors.grey.shade50,
    Colors.grey.shade100,
    Colors.grey.shade200,
    Colors.grey.shade300,
    Colors.grey.shade400,
    Colors.grey.shade500,
    Colors.grey.shade600,
    Colors.grey.shade700,
    Colors.grey.shade800,
    Colors.grey.shade900
  ];
  static final List<Color> blueGreyList = [
    Colors.blueGrey.shade50,
    Colors.blueGrey.shade100,
    Colors.blueGrey.shade200,
    Colors.blueGrey.shade300,
    Colors.blueGrey.shade400,
    Colors.blueGrey.shade500,
    Colors.blueGrey.shade600,
    Colors.blueGrey.shade700,
    Colors.blueGrey.shade800,
    Colors.blueGrey.shade900
  ];
}
